### ISSUE TITLE
Milestone #3 

### ISSUE THREAD

**Issue by hfboyce** [UBC-MDS/ColourblindR#16]
**Milestone 3 list:**

- [x] README - usage/ installation
- [x]  Functions - (one for each colourblind variant) (see second issue for completion status) 
- [x]  License in both python and R 
- [x] Passes ALL tests /  writing additional test cases for both your Python and R packages  
- [x] documentation
- [x]  vignette for R (edited) 
- [x] branch coverage (R AND PYTHON)

(side note: continue using GitHub's issue tracker and milestone feature to plan the milestone. In particular, you must document your tasks in issues and assign each issue to Milestone 3)
