### ISSUE TITLE
Milestone 4 Todo List 

### ISSUE THREAD

**Issue by hfboyce** [UBC-MDS/ColourblindR#57]
- [x] **Fix error in test_histogram**
---
- [x] R: Add appropriate exception handler for all functions.
- [x] Python: Add appropriate exception handler for all functions.
---
- [x] R: Add adequate integration tests in each package, if applicable. (  I don't understand what this is )
- [x] Python: Add adequate integration tests in each package, if applicable. ( I don't understand what this is )
---
- [x] R: Set up continuous integration testing using Travis and add a passing build stamp for each package README files. 
- [x] Python Set up continuous integration testing using Travis and add a passing build stamp for each package README files. 
---
- [x] R: In your README, include a clear description of how to install your package and call your functions. 
- [x] Python: In your README, include a clear description of how to install your package and call your functions.  
---
- [x] R: Also include an example with a toy dataset and a screenshot of the output when you run tests
- [x] Python: Also include an example with a toy dataset and a screenshot of the output when you run tests
---
-  [x] Individually report the contributions of each team member by filling out this standard form. This is worth 10% of your grade and is due the morning after the final project submission, i.e., on Sunday, March 10th at noon.

**Comment by hfboyce** [comment]
Ok team for tomorrow's lab I think we concentrate on exploring what's going on with test_histogram and I will have Travis on Colourblind8 done too. 
Second priority is figuring out what " appropriate exception handler " and "adequate integration tests" are. 
 Then it's smooth sailing.

**Comment by ian-flores** [comment]
We figured it out together yesterday.
